name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "develop", "release", "master" ]
    
  pull_request:
    branches: [ "release", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
  
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Packages
      run: nuget restore Framework.sln

    - name: Build solution
      run: msbuild Framework.sln -t:rebuild -property:Configuration=Release

    - name: Nuget pack (develop branch)
      if: github.event.ref == 'refs/heads/develop'
      run: |
        nuget pack ./Framework -NonInteractive -Verbosity detailed -SolutionDirectory . -OutputDirectory ./Framework/bin/develop Framework.sln 

    - name: Nuget pack (master branch)
      if: github.event.ref == 'refs/heads/master'
      run: |
        nuget pack ./Framework -NonInteractive -SolutionDirectory . -OutputDirectory ./Framework/bin/release Framework.sln 

    - name: NuGet package publish
      if: github.event.ref == 'refs/heads/master'
      run: |
        dotnet nuget push ./Framework/bin/release/BOG.Framework.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ vars.NUGET_SOURCE }} --skip-duplicate
